### ISSUE TITLE
Empty edit-me.txt is confusing students

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/welcome-to-learn-5#10]
I've noticed that many new students ask about the fact that `edit-me.txt` is empty, and are not sure what to do next. I believe this is because step 6 makes multiple references to "the content" of that file, leading students to believe that the file should already contain some text:

> To pass this lab, make any change to the content of the `edit-me.txt` file. You can do this by clicking on the name of the file in the file browser in the left pane; its contents will load in the text editor. Type into the text editor to change the contents of the file, then save your changes.

Therefore, I would suggest adding some placeholder text to this file. I think "The quick brown fox jumps over the lazy dog" or some lorem ipsum text would do just fine. Happy to make a PR for this if desired. 👍 

cc @aturkewi

**Comment by aturkewi** [comment]
Added note in #9 letting students know file is starting off blank.
