### ISSUE TITLE
what to do when no lessons are pre-loaded into IDE?

### ISSUE THREAD

**Issue by laheraestefania** [learn-co-curriculum/welcome-to-learn-5#16]
when I type in learn I get: You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory and try again. but I can't CD because my labs folder is empty
<img width="766" alt="screen shot 2016-12-14 at 6 58 42 pm" src="https://cloud.githubusercontent.com/assets/21985890/21206354/7020c606-c22f-11e6-9ee8-bb82b3968095.png">

**Comment by gj** [comment]
Hey @laheraestefania, if you use [the Ask a Question feature](https://help.learn.co/hc/en-us/articles/229825587-Where-can-I-ask-a-question-about-a-lesson-), someone can definitely help you out with this.

**Comment by aturkewi** [comment]
Hey @laheraestefania 
@gj is correct here. The best way to get a quick resolution to this is to use Ask A Question in Learn :) We have Learn Experts available to give immediate support from 9am-1am (Eastern US time).
