### ISSUE TITLE
Two Folders No files 

### ISSUE THREAD

**Issue by JamiliaW38** [learn-co-curriculum/welcome-to-learn-5#24]

**Comment by JamiliaW38** [comment]
I am at the beginging of my 1st lab. there are two folders titled "code" and "labs" there is no files inside both folders. I am looking for the edit-me.text file. Was I suppose to clone an fork those files manually?

**Comment by aturkewi** [comment]
Hey @JamiliaW38 the cloning and forking _should_ have been done for you when you used the Open button in Learn. 
If that did not work, the best way to get immediate support is to use the Ask A Question button in Learn. We have Learn Experts on from 9am-1am Eastern US times to help :)

Sorry for the slow reply, but if you still need a hand, they'll be able to give immediate support :)
