### ISSUE TITLE
Loading your remote code...

### ISSUE THREAD

**Issue by dortega5185** [learn-co-curriculum/welcome-to-learn-5#29]
Hello, my problem is after I click the Open tab it opens the Learn IDE but it stays on the loading screen. Yesterday night it loaded fully like it showed on the picture but it wasn't reacting to my learn+ enter. Appreciate any help.

**Comment by aturkewi** [comment]
Hey @dortega5185 sorry for the slow reply here. 
If you need a hand completing this lab or something isn't working as you would expect with the Learn IDE, the best place to get help is by clicking the Ask A Question button in Learn. We have Learn Experts on there from 9am - 1am to provide immediate support. That way you won't have to wait months to hear back from some one here :(

Again, sorry about the long wait, but the Learn Experts will definitely be able to help with this :)
