### ISSUE TITLE
Failing local tests - please help

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/welcome-to-learn-5#30]
/usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rspec/core/confi
guration.rb:1327:in `load': /home/triciadros-51041/code/labs/welcome-to-l
earn-5-welcome-000/spec/first.lab_spec.rb:7: syntax error, unexpected end
-of-input, expecting keyword_end (SyntaxError)                           
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/configuration.rb:1327:in `block in load_spec_files'              
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/configuration.rb:1325:in `each'                                  
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/configuration.rb:1325:in `load_spec_files'                       
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/runner.rb:102:in `setup'                                         
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/runner.rb:88:in `run'                                            
 from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/runner.rb:73:in `run'                                            
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/lib/rsp
ec/core/runner.rb:41:in `invoke'                                         
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.3.2/exe/rsp
ec:4:in `<top (required)>'                                               
        from /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:22:in `load'       
        from /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:22:in `<main>'     
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:
in `eval'                                                                
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:
in `<main>'                                                              
[22:41:01] (master) welcome-to-learn-5-welcome-000                       
// ♥ learn 

when I first typed learn and enter...I did not get an error message I got a welcome message

**Comment by aturkewi** [comment]
Hey @tricia3dros sorry for the slow reply here. 
If you need a hand completing this lab or something isn't working as you would expect with the Learn IDE, the best place to get help is by clicking the Ask A Question button in Learn. We have Learn Experts on there from 9am - 1am to provide immediate support. That way you won't have to wait months to hear back from some one here :(

Again, sorry about the long wait, but the Learn Experts will definitely be able to help with this :)
