### ISSUE TITLE
Is it essential to learn jQuery nowadays or it can be substituted with something else.

### ISSUE THREAD

**Issue by betterversion** [learn-co-curriculum/welcome-to-learn-5#31]

**Comment by aturkewi** [comment]
Hey @betterversion that's a great question.

This isn't really any issue with this lab though. The best place to ask something like this would be using Ask A Question in Learn or in the learn-co slack group.

My short answer would be that you probably _do_ want to know a few things in jQuery and how to use it, but I've also seen a lot of place looking to move away from jQuery. In the end, it's really going to come down to where you end up working and what they already have in place :)
