### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/welcome-to-learn-5#33]
Even though I completed the 1st Lab. It's just saying that I didn't complete the class.

**Comment by aturkewi** [comment]
@prekapal you'll have to make sure all lights are green to proceed past the welcome track.

And I'm sorry for the slow reply here. The best way to get immediate assistance with a lab is the Ask A Question button in Learn.  We staff it with Learn Experts from 9am - 1am Easter time and they're always happy to help :)
