### ISSUE TITLE
I've changed edit-me.txt successfully yet it still says local test failed. Ive reloaded the web page and it still says local test failed. the submit was successful though.

### ISSUE THREAD

**Issue by mbrewer81** [learn-co-curriculum/welcome-to-learn-5#35]
I followed all the steps and tried to find the answer in the Q&A as a previous user encountered a similar problem.

Mine shows me 
"You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory and 
try again."

**Comment by aturkewi** [comment]
Hey @mbrewer81 the submit is pretty much always successful, but it doesn't mean that the tests ran properly. To get back into the lab directory, check out this help center article: http://help.learn.co/workflow-tips/running-tests/you-dont-appear-to-be-in-a-learn-lessons-directory

Also, sorry about the slow reply here. This isn't the best way to get quick help when you're stuck. For something like this, I would recommend using the Ask A Question button in Learn :) We have Learn Experts online from 9am - 1am to give immediate support!
