### ISSUE TITLE
IDE Lab

### ISSUE THREAD

**Issue by allimaddionah** [learn-co-curriculum/welcome-to-learn-5#36]
Hello,
I had to redownload the IDE since my other computer crashed. On the last one, it worked fine, but this download is missing the file bar. I have a screenshot I am attaching. I am not sure what to do.
![screen shot 2017-03-13 at 4 08 58 pm](https://cloud.githubusercontent.com/assets/26387885/23873208/9649a280-0807-11e7-98ba-d858f3049956.png)

**Comment by aturkewi** [comment]
Hey @allimaddionah the best way to get help with this kind of issue is to use the Ask A Question button in Learn. We have Learn Experts online from 9am to 1am Easter times and they're always happy to help :)
