### ISSUE TITLE
local test failed

### ISSUE THREAD

**Issue by rick-love** [learn-co-curriculum/welcome-to-learn-5#38]
My local test failed, why? I'm using a windows based pc, is that OK?

**Comment by aturkewi** [comment]
Hey @rick-love sorry for the slow reply here. The best place to get help with something like this is the Ask A Question button on Learn. We have Learn Experts online from 9am to 1am Easter time and they're always happy to help :)

My first guess as to why the tests are failing is that you may need to still edit the file talked about in this lesson and then make sure to save the file before running `learn`. If you still need a hand, you can check out the video walkthrough at the end of this lab and use Ask A Question for any more help :)
