### ISSUE TITLE
failed installation

### ISSUE THREAD

**Issue by deeanna81** [learn-co-curriculum/welcome-to-learn-5#39]
Once the file is downloaded and after I wait for it to run it finishes with a installation has failed box: There was an error while installing application. Check the setup log for more information and contact the author.

**Comment by aturkewi** [comment]
Hey @deeanna81 thanks for letting us know and sorry for the slow reply. 
It will be a bit difficult to trouble shoot this issue through this format. The best way to get help with this is to use the Ask A Question button in Learn. We have Learn Experts online from 9am to 1am and they're always happy to provide immediate help :)
