### ISSUE TITLE
fail local test

### ISSUE THREAD

**Issue by letristandan** [learn-co-curriculum/welcome-to-learn-5#40]
Hello,
it said i failed the local test. I tried to fix the problem but without success. Anyone can help me out please. Thanks.

Tristan Dan le
letristandan@gmail.com

**Comment by aturkewi** [comment]
Hey @letristandan thanks for posting here :)
Sorry for the slow reply, but the best place to get immediate help would be the Ask A Question button on Learn. We have Learn Experts online from 9am to 1am Easter time to provide immediate support :)
