### ISSUE TITLE
open button doesn't open lab

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/welcome-to-learn-5#41]
Hi - I am having the same issue as familiamichael... clicking open doesn't launch the lab. I'd appreciate a bit of help. Can't wait to get started!

**Comment by aturkewi** [comment]
Hey @jea2121 sorry about the slow reply here. The best place to get hep with this kind of issue though would be through the Ask A Question button on Learn. The Learn Experts will be able to provide live and immediate support :) They're online from 9am to 1am Easter time!
