### ISSUE TITLE
Having issues with learn IDE

### ISSUE THREAD

**Issue by ramoslam** [learn-co-curriculum/welcome-to-learn-5#43]
## Hi there! I opened for the first time Learn IDE and I can`t do anything with it. It keeps on saying:
You don't appear to be in a Learn lesson's directory. Please cd to an app ropriate directory and try again.

**Comment by aturkewi** [comment]
Hey @ramoslam sorry about the slow reply here. The best place to get hep with this kind of issue though would be through the Ask A Question button on Learn. The Learn Experts will be able to provide live and immediate support :) They're online from 9am to 1am Easter time!

Regarding that specific error message, this Help Center article may be what you're looking for: http://help.learn.co/workflow-tips/running-tests/you-dont-appear-to-be-in-a-learn-lessons-directory
