### ISSUE TITLE
How do I cd into the lesson directory?

### ISSUE THREAD

**Issue by spiritualgangster** [learn-co-curriculum/welcome-to-learn-5#48]
I'm in the edit-me.txt lab but when I try to commit "learn submit" I receive this message:

It doesn't look like you're in a lesson directory.                                              
Please cd into an appropriate directory and try again.

**Comment by aturkewi** [comment]
Hi @spiritualgangster this is really a better question for the Ask A Question button as opposed to a GitHub issue. Turn around times here tend to be much slower and this section is more for 'the lab is broken' than 'help solving the lab'. If you use the Ask A Question in Learn, we have a team on there from 9am to 1am Eastern US time to help answer this type of question :)
All that being said, I think this may help you out: http://help.learn.co/workflow-tips/running-tests/you-dont-appear-to-be-in-a-learn-lessons-directory
