### ISSUE TITLE
Issues loading repo

### ISSUE THREAD

**Issue by comadivine** [learn-co-curriculum/welcome-to-learn-5#52]
To preface, I am using the Learn IDE on Parrot Linux (Deb).  It installed fine, but I'm running into an issue.

"Open" on the Your First Lab page does not properly load the repo / ie does nothing with the Learn IDE.
Downloading the directory directly from github is also producing no results, and attempting to open the extracted folder is yielding no result.

My question:  is this a result of the Learn IDE that is known for Linux / Debian, and if so, since it's based on Atom, is there any reason the base Atom package would not suffice for these courses?  My desktop is Windows, so if I have to I can use it, but I'd prefer not if possible.

Thanks for your assistance.

**Comment by aturkewi** [comment]
Hey @comadivine thanks for reaching out!

The Open button does not work on Linux unfortunately. In this case, the best option is to manually open the lab by typing the command `learn open` into the IDE terminal. You can also refer to this article for future labs if you run into an issue: http://help.learn.co/the-learn-ide/common-ide-questions/learn-open-button-issues

I'll also see if I can update this lesson to make this clear :)

Please feel free to re-open this issue if you still need a hand.
