### ISSUE TITLE
Accessing my First Lab

### ISSUE THREAD

**Issue by prmeister89** [learn-co-curriculum/welcome-to-learn-5#59]
Hello,

I can't seem to access my first Lab.  Whenever I try to open the Lab in the Learn IDE, I get the follow error code:

[23:05:22] code
// ♥ learn open
Getting current lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.

I've tried asking someone for assistance in the "Ask A Question" menu on the learn.co website and they were unable to help me in this regard.  I'm not sure how to resolve this and would like to start my Pre-Work.  Any help would be greatly appreciated.  Thank you.

Sincerely,

Peter Meister

**Comment by aturkewi** [comment]
Hey @prmeister89 Thanks so much for posting what you saw in the terminal :) This is really helpful for solving issues.

For this issue though, the Technical Coaches would be the best team to help you with this. If they were unable to help you solve this, then they will create a support ticket for you. 
I'm taking a look at your account on Learn and it looks like you have passed this lab, so it seems like things are all set now?

If you still need a hand though, please use Ask A Question to contact the Technical Coaches and they will put in a support ticket if they cannot get you past the first lab. 
I'm
