### ISSUE TITLE
Failed Local Test

### ISSUE THREAD

**Issue by Jozefi87** [learn-co-curriculum/welcome-to-learn-5#6]
..hi there ..I'm having challenge with local taste(failed local test) ...how to pass to the next level..so how to overcome this obstacle...thanks so much...

**Comment by aturkewi** [comment]
Hey @Jozefi87 it looks like you've moved on past this lab, so I'm going to close this issue. If you run into any other issues as you're moving through Learn though, feel free to try the Ask A Question button to get a hand!
