### ISSUE TITLE
Connectivity Issues?

### ISSUE THREAD

**Issue by JohnathanCh** [learn-co-curriculum/welcome-to-learn-5#60]
I keep having connectivity issues. I opened the lab "learn open" I then made the appropriate changes to edit-me.txt, tested it locally by running "learn" and received this message

First Lab: you made an edit to edit-me.txt Finished in 0.00375 seconds (files took 0.31344 seconds to load) 1 example, 0 failures

Then when I try to submit it "learn submit" I get this message: It looks like you have no changes to commit. Will still try updating your submission... Pushing changes to GitHub... /usr/local/rvm/gems/ruby-2.3.1/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/home/johnchriest-1065 47/code/labs/welcome-to-learn-5-welcome-000/.git' '--work-tree=/home/johnchriest-106547/code/labs/welcome-to-learn-5 -welcome-000' push 'origin' 'master' 2>&1:ERROR: Permission to learn-co-students/welcome-to-learn-5-welcome-000.git denied to learn-ide-user. (Git::GitExecuteError) fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. 

This was followed by a bunch more links and file directories

**Comment by aturkewi** [comment]
@JohnathanCh thanks so much for raising an issue and letting us know! I do not think that this is an issue with this lab specifically though, but perhaps with how the IDE is working for you at the moment. 
The best place to get support with an IDE issue would be to use the Ask A Question button on Learn :) The Technical Coach team is on there from 9am-1am Eastern US time every day to provide live support for this :)

I'm going to close this issue for now, but please use the Ask A Question button when you're next free to get immediate support.

Happy coding!

**Comment by JohnathanCh** [comment]
I actually got it resolved. It was a problem with connecting to GitHub.

Thanks
