### ISSUE TITLE
I'm getting the message when attempting to install the IDE

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/welcome-to-learn-5#62]
When I try to install the IDE on windows 7, I receive the message "installation has failed", "The was an error while installing the application. Check the setup log for more information and contact the author".
![error](https://user-images.githubusercontent.com/26488480/29150738-86d81a4e-7d4a-11e7-80bd-d2d7e11a2331.png)

**Comment by aturkewi** [comment]
Hey @Fan-jo I'm guessing you may have resolved this given that you closed the issue, but I figured I would try and pass along some helpful advice in nay case :)

For something like this, the best way to get help is to use the Ask A Question button on the Learn platform. That button is staff with a technical coach staff from 9am to 1am Eastern. Another great place to check is the Help Center. Here is an article on problems installing the Learn IDE for example: http://help.learn.co/the-learn-ide/the-basics-of-the-learn-ide/cannot-install-the-learn-ide

I'm sorry you ran into issues with the install, but if you still need a hand, try one of those avenues for more immediate support :)

Best of luck!
