### ISSUE TITLE
I don't know how to start

### ISSUE THREAD

**Issue by Code-ein** [learn-co-curriculum/welcome-to-learn-5#63]
After I click OPEN, a black window opens and I don't know how to proceed.
I need to run the lab's tests with the learn CLI command, which I don't know what it is.
Please help me!
Thanks

**Comment by aturkewi** [comment]
Hey @Code-ein the best place to get immediate help with this kind of issue is the Ask A Question button on the Learn platform. The Technical Coach team staffs that channel from 9am to 1am Eastern US time.

I'm going to close this issue for now, but if you still need a hand, please reach out and they'll be able to help :)
