### ISSUE TITLE
Learn crashes on load in psych.rb

### ISSUE THREAD

**Issue by etagavilla** [learn-co-curriculum/welcome-to-learn-5#65]
Below is the log  + backtrace:
Looking for lesson...
Sorry, there seems to be a problem with this lesson. Please submit a bug report to bugs@learn.co and try again later.
If you'd like to work on your next lesson now, type: learn next
[04:48:09] (master) welcome-to-learn-5-welcome-000
// ♥ learn
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): could not find expected ':' whil
at line 12 column 1 (Psych::SyntaxError)
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:325:in `parse'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:252:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/strategies/green_onion.rb:53:in `yaml
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/strategies/green_onion.rb:49:in `gree
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/strategies/green_onion.rb:16:in `dete
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/runner.rb:33:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/runner.rb:33:in `detect'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/runner.rb:33:in `strategy'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/lib/learn_test/runner.rb:11:in `initialize'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/bin/learn-test:60:in `new'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.4.2/bin/learn-test:60:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
