### ISSUE TITLE
Cant open Learn IDE

### ISSUE THREAD

**Issue by cgarey2014** [learn-co-curriculum/welcome-to-learn-5#68]
Accidentally opened in temporary directory, now the open button will not work. Running Debian

**Comment by sgharms** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
