### ISSUE TITLE
Waiting to hear back

### ISSUE THREAD

**Issue by georgelgore** [learn-co-curriculum/welcome-to-learn-5#69]
worked with Ian Valentine on this but not sure if a ticket was created. I need to get access to the accepted student materials on this github account. For some reason my other one, ggore13, has access and im not able to submit my labs through the terminal.

**Comment by DanielSeehausen** [comment]
Hi there! This request sounds like an improvement to the Learn platform. Raising issues on GitHub should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface improvements. You can reach them at support@learn.co. Alternatively, if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue and we will try to discern a proper path to resolution.
